### ISSUE TITLE
Add commit support to docker driver

### ISSUE THREAD

**Issue by easeway** [evo-cloud/hmake#24]
If `commit` is present, after the normal execution of docker target, the container can be committed back to an image. This gives people more flexibility (`docker run` plus `docker commit`) to build images, instead of using `docker build` only.

Both `docker build` and `docker commit` should support extra tags instead of one, and supporting labels too.

E.g. for `docker build`, property `image` can be used as the primary tag, while additional `tags` property can specify more tags.

For `docker commit`, the value of `commit` specifies the primary tag, and when `tags` is present, additional `docker tag` command should be used.

**Comment by easeway** [comment]
tags/labels are supported, as well as other command line options.

**Comment by easeway** [comment]
The schema is:

``` yaml
targets:
  task-with-commit:
    image: alpine:latest
    cmds:
        - run something modify the file system
    commit:
        - myimage:latest
        - myimage:1.0.0
        - host:5000/myrepo/myimage:latest
        - host:5000/myrepo/myimage:1.0.0
```

The actual work done is:
- `docker run ...` with `cmds` from `alpine:latest`
- `docker commit CONTAINER-ID myimage:latest`
- `docker tag myimage:latest myimage:1.0.0`
- `docker tag myimage:latest host:5000/myimage:latest`
- `docker tag myimage:latest host:5000/myimage:1.0.0`
