### ISSUE TITLE
Target Expansion

### ISSUE THREAD

**Issue by easeway** [evo-cloud/hmake#83]
Currently targets are duplicated to support minor difference, e.g.

```
targets:
  build-amd64:
    after: ...
    watches: ...
    env: ...
    cmds:
      - ...
      - build.sh amd64

  build-arm:
    after: ...
    watches: ...
    env: ...
    cmds:
      - ...
      - build.sh arm
```

In the example, the only difference is `amd64` vs `arm`, but rest information is duplicated and redundant.

Recommend target expansion:

```
targets:
  build-[arch:amd64|arm]:
    after: ...
    watches: ...
    cmds:
      - ...
      - build.sh $arch
```

The target `build-[arch:amd64|arm]` is expanded to two targets: `build-amd64` and `build-arm`.

**Comment by easeway** [comment]
The final schema is

```
targets:
  build-[arch:amd64,arm]:
    after: ...
    watches: ...
    cmds:
      - ...
      - build.sh $[arch]
```

Resolved in #85
