### ISSUE TITLE
Dependency is handled incorrectly

### ISSUE THREAD

**Issue by easeway** [evo-cloud/hmake#88]
For example, with 3 targets:

``` yaml
targets:
  base:
    watches:
        - somefile
    cmds:
        - do something
  work1:
    after:
      - base
    cmds:
      - do something
  work2:
    after:
      - base
    cmds:
      - do something
```

Change `somefile`, and do `hmake work1`, it rebuilds `base` and `work1`. Then do `hmake work2`, it skips `work2`. The expected result is it should rebuild `work2`.

Change `somefile` and do `hmake work1 work2`, it will rebuild `base`, `work1`, `work2`.
