### ISSUE TITLE
Support services during targets lifecycle

### ISSUE THREAD

**Issue by easeway** [evo-cloud/hmake#93]
Introduce `service` (aka background) as special target type. That type of target will run in the background until all other targets complete.

E.g.

```
targets:
  influxdb:
    description: run influxdb
    background: true
    cmds:
        - run_influxdb.sh

  app1:
    description: my app
    after:
       - influxdb
```

The commands in `service` target must finish to indicate the readiness of the service. For other targets consuming the `service` target, the existing dependency mechanism is re-used.

The only difference in implementation of a `service` target is:

- the wrapper script should not exit
- the container keep running until all other non-service targets complete.
