### ISSUE TITLE
Support command targets

### ISSUE THREAD

**Issue by easeway** [evo-cloud/hmake#94]
Command targets is a special target which accepts additional command-line arguments. This type of target can only be used as the first target on the command line, otherwise it becomes a normal target.

E.g.

```
targets:
  mycli:
    description: the cli target
    command: true
    cmd:
        - do something $1 $2
        - do all the things "$@"
```

When invoked using `hmake mycli arg1 arg2`, the arguments `arg1`, `arg2` will be passed to the target.
But if invoked using `hmake sometarget mycli`, then `mycli` is invoked as a normal target without command line arguments.
